In [ ]:
!pip install fiftyone

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 7.9/7.9 MB 17.5 MB/s eta 0:00:00
   ---------------------------------------- 108.9/108.9 kB 6.2 MB/s eta 0:00:00
   --------------------------------------- 192.5/192.5 kB 11.4 MB/s eta 0:00:00
   ---------------------------------------- 89.6/89.6 kB ? eta 0:00:00
   ---------------------------------------- 20.1/20.1 MB 10.6 MB/s eta 0:00:00
   ---------------------------------------- 59.9/59.9 kB 3.1 MB/s eta 0:00:00
   ---------------------------------------- 133.3/133.3 kB ? eta 0:00:00
   ---------------------------------------- 65.9/65.9 MB 18.2 MB/s eta 0:00:00
   ---------------------------------------- 74.3/74.3 kB 4.0 MB/s eta 0:00:00
   --------------------------------------- 484.6/484.6 kB 15.3 MB/s eta 0:00:00
   ---------------------------------------- 71.9/71.9 kB 3.9 MB/s eta 0:00:00
   --------------------------------------- 942.9/942.9 kB 19.8 MB/s e

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.2.2 

In [ ]:
import fiftyone as fo
import fiftyone.zoo as foz

print(foz.list_zoo_datasets())

dataset = foz.load_zoo_dataset("coco-2017", split="validation")

dataset.name = "coco-2017-validation-example"
dataset.persistent = True

session = fo.launch_app(dataset)

Migrating database to v0.23.8
['activitynet-100', 'activitynet-200', 'bdd100k', 'caltech101', 'caltech256', 'cifar10', 'cifar100', 'cityscapes', 'coco-2014', 'coco-2017', 'fashion-mnist', 'fiw', 'hmdb51', 'imagenet-2012', 'imagenet-sample', 'kinetics-400', 'kinetics-600', 'kinetics-700', 'kinetics-700-2020', 'kitti', 'kitti-multiview', 'lfw', 'mnist', 'open-images-v6', 'open-images-v7', 'places', 'quickstart', 'quickstart-geo', 'quickstart-groups', 'quickstart-video', 'sama-coco', 'ucf101', 'voc-2007', 'voc-2012']
 100% |██████|    1.9Gb/1.9Gb [19.1s elapsed, 0s remaining, 113.8Mb/s]      
Extracting annotations to 'C:\Users\Neiv Gupta\fiftyone\coco-2017\raw\instances_val2017.json'
 100% |██████|    6.1Gb/6.1Gb [55.9s elapsed, 0s remaining, 125.7Mb/s]      
Extracting images to 'C:\Users\Neiv Gupta\fiftyone\coco-2017\validation\data'
Writing annotations to 'C:\Users\Neiv Gupta\fiftyone\coco-2017\validation\labels.json'
Dataset info written to 'C:\Users\Neiv Gupta\fiftyone\coco-2017\inf


Welcome to

███████╗██╗███████╗████████╗██╗   ██╗ ██████╗ ███╗   ██╗███████╗
██╔════╝██║██╔════╝╚══██╔══╝╚██╗ ██╔╝██╔═══██╗████╗  ██║██╔════╝
█████╗  ██║█████╗     ██║    ╚████╔╝ ██║   ██║██╔██╗ ██║█████╗
██╔══╝  ██║██╔══╝     ██║     ╚██╔╝  ██║   ██║██║╚██╗██║██╔══╝
██║     ██║██║        ██║      ██║   ╚██████╔╝██║ ╚████║███████╗
╚═╝     ╚═╝╚═╝        ╚═╝      ╚═╝    ╚═════╝ ╚═╝  ╚═══╝╚══════╝ v0.23.8

If you're finding FiftyOne helpful, here's how you can get involved:

|
|  ⭐⭐⭐ Give the project a star on GitHub ⭐⭐⭐
|  https://github.com/voxel51/fiftyone
|
|  🚀🚀🚀 Join the FiftyOne Slack community 🚀🚀🚀
|  https://slack.voxel51.com
|



In [ ]:
import numpy as np
import open_clip

In [ ]:
from PIL import Image
import requests
import torch
import os
from os import listdir

model, preprocess = open_clip.create_model_from_pretrained('hf-hub:laion/CLIP-ViT-g-14-laion2B-s12B-b42K')
tokenizer = open_clip.get_tokenizer('hf-hub:laion/CLIP-ViT-g-14-laion2B-s12B-b42K')

In [ ]:
data_dir = 'C:/Users/Neiv Gupta/fiftyone/coco-2017/validation/data'
embedding_dir = 'C:/Users/Neiv Gupta/fiftyone/coco-2017/validation'

def get_image_embedding(image_path):
    image = Image.open(image_path)
    image = preprocess(image).unsqueeze(0)
    with torch.no_grad(), torch.cuda.amp.autocast():
        image_features = model.encode_image(image)
    return image_features.squeeze().numpy()

for dir_image in os.listdir(data_dir):
    print(dir_image)
    embedding = get_image_embedding(os.path.join(folder_dir, dir_image))
    embedding_path = os.path.join(embedding_dir, f'{os.path.splitext(dir_image)[0]}.npy')
    np.save(embedding_path, embedding)
    print(embedding)




000000000139.jpg
[ 0.47830567  0.927796    0.28704354 ...  0.24531746 -0.6568091
  0.24830817]
000000000285.jpg
[0.5624703  0.01401793 0.07991153 ... 0.81647795 0.8801561  0.45600078]
000000000632.jpg
[ 0.11358737 -0.83596396 -0.14531587 ...  1.0565377   0.81593865
 -0.7553845 ]
000000000724.jpg
[ 1.8219318   0.5757748  -0.8918067  ...  0.28355017  0.2337568
 -0.7776262 ]
000000000776.jpg
[-0.1460785  -1.0440753  -0.13940677 ...  0.34662414  0.70454645
  0.2961624 ]
000000000785.jpg
[ 0.515964   -0.03847292 -1.0153091  ... -0.33119965  0.69081223
 -0.62559295]
000000000802.jpg
[ 0.5790792   0.69624335 -0.28286207 ...  0.8043517   0.7996119
  0.34969866]
000000000872.jpg
[ 0.4963398  -0.12461187 -0.4747745  ...  0.18693022  1.2132256
 -1.0792828 ]
000000000885.jpg
[-0.28800514 -0.18377751 -0.9106662  ... -0.32917175  0.4188395
 -0.5265533 ]
000000001000.jpg
[-0.8860055  -0.7626852  -0.02265719 ...  1.3445519  -0.06484435
 -0.3176105 ]
000000001268.jpg
[ 0.6410082  -1.1198026   0.0656413

[ 0.09015028  0.52007926  0.5788402  ... -0.20938447 -1.0094953
 -0.3441024 ]
000000008629.jpg
[ 0.2584213   1.4933115   0.27858615 ...  1.3150066  -0.10727663
  0.35252422]
000000008690.jpg
[-0.11069953  2.0758111   1.3782223  ...  0.4522619   0.32307154
  0.7095817 ]
000000008762.jpg
[ 1.8569856   0.7703815   0.21659987 ...  0.33501086 -0.06742754
 -0.7714108 ]
000000008844.jpg
[ 0.01279873  1.8016732  -0.24049804 ...  0.08861502 -0.10348143
 -0.6173873 ]
000000008899.jpg
[-0.73530406 -0.263532   -0.31948966 ...  0.18953304 -0.91135156
  0.46909025]
000000009378.jpg
[-0.1575394  -0.8555513   0.07226204 ... -0.47081533  0.5564375
 -0.6906394 ]
000000009400.jpg
[ 1.4748988   0.44105294  0.04060075 ...  0.0453815  -0.15312786
 -1.1652983 ]
000000009448.jpg
[-1.2252245   0.41235486  1.0607055  ... -0.41485438 -0.47426483
 -0.09809598]
000000009483.jpg
[-0.23892719 -0.12175434  0.30341613 ...  0.171992   -0.3399446
  0.35510638]
000000009590.jpg
[-0.39115122 -0.11594892 -0.15414436 ... -0

[ 1.2121412   0.4847298  -0.7021559  ... -0.14028591  0.9786263
 -0.65396154]
000000017436.jpg
[ 0.6302291   0.2508539   0.10027358 ... -0.27767247 -0.14133634
  1.1268284 ]
000000017627.jpg
[ 1.4816681   0.48991057 -0.9420291  ... -0.99399173 -0.6131282
 -1.1204927 ]
000000017714.jpg
[ 0.01572277  1.1200495   0.17944889 ...  0.6185764   0.14793542
 -1.3863181 ]
000000017899.jpg
[ 0.3180812  -0.09288702  0.84875846 ...  0.22216552  0.67699426
  0.01509053]
000000017905.jpg
[ 0.44131073  0.5785772  -1.414956   ... -1.0201099  -0.5677163
 -2.0109603 ]
000000017959.jpg
[ 0.6174452  -1.0876068  -0.5304726  ...  0.11888343  0.82734686
  0.20461042]
000000018150.jpg
[ 0.45111832 -1.2884383   1.7911822  ...  0.63253236 -0.68123275
  0.635986  ]
000000018193.jpg
[-0.45938823 -0.65858525 -0.719657   ...  0.47154886 -0.42877698
 -0.5819929 ]
000000018380.jpg
[ 0.29820725 -0.3729127   0.30822057 ...  0.41582254  0.01825425
 -0.06569178]
000000018491.jpg
[ 0.04274678 -0.9560475  -0.96581984 ...  0

[ 0.5791415   1.464718    0.48310316 ... -0.04499177 -0.04602864
 -1.335994  ]
000000027186.jpg
[ 0.15652151  0.86706084  1.379162   ... -0.04274524  0.37513402
  0.38521045]
000000027620.jpg
[ 0.07597533 -0.76028633  0.11946974 ...  0.37075886  0.7580729
 -0.46926063]
000000027696.jpg
[-0.08080733  0.79931426  0.6401352  ...  1.573258    0.9774246
  1.2682996 ]
000000027768.jpg
[0.30609083 0.9137815  0.10342867 ... 0.7939162  0.20956786 0.6007118 ]
000000027932.jpg
[-0.2639536   0.29009232  0.8853953  ...  0.21096593  0.00211317
 -0.08703063]
000000027972.jpg
[ 0.61502314 -0.7397361   0.00791834 ... -0.2548334   0.34036398
 -0.1324674 ]
000000027982.jpg
[ 0.51668143  0.47171298 -0.6910214  ... -0.49937677  0.77075005
 -0.40323466]
000000028285.jpg
[-0.18879546  1.327161    0.5682517  ...  0.6372551   0.5909656
  0.44852608]
000000028449.jpg
[ 0.96772146 -0.00917793 -0.28046712 ...  0.59688485 -0.29486355
 -0.7934318 ]
000000028452.jpg
[-0.414272   -0.8522656  -0.44980627 ... -0.007125

[-1.7101327   1.3354987  -0.21469475 ...  0.17047319  0.50747585
 -1.2018033 ]
000000037777.jpg
[ 0.01498665  1.1088114  -0.46352914 ...  0.68608403 -0.48603845
  0.7772711 ]
000000037988.jpg
[-1.0490185   0.77457166 -0.65753037 ...  0.02316155  0.43859434
 -0.5376542 ]
000000038048.jpg
[ 0.4397547   0.2140359  -1.1772124  ... -0.11507391  0.20575365
 -0.20510979]
000000038070.jpg
[ 0.14323333 -0.00465346 -0.7775089  ... -0.03937765  1.224812
 -0.6758579 ]
000000038118.jpg
[-0.8273599   0.2482777  -0.02363776 ...  0.3970136   1.2180657
 -0.50320303]
000000038210.jpg
[-0.7958422  -0.18372299 -0.18360828 ...  0.30880457 -0.06428228
 -1.190423  ]
000000038576.jpg
[ 1.4164957e+00 -4.0147519e-01 -3.7906867e-02 ...  1.5874459e+00
 -1.3765114e-03  2.2684702e-01]
000000038678.jpg
[-0.01657578  1.4592779  -0.9541707  ...  0.01467309 -0.58724326
 -1.2565392 ]
000000038825.jpg
[ 1.2629125   0.51813865  0.46071085 ...  0.42298993 -0.52182007
 -0.45289892]
000000038829.jpg
[ 0.8337622   1.146076   

[-0.10570058  2.684658    0.9817408  ... -0.02678655  0.9387969
  0.3234443 ]
000000049091.jpg
[ 0.07856007  0.17656654 -0.5481798  ... -0.34673476 -0.28198734
 -0.34680617]
000000049259.jpg
[ 0.2809152  -0.08586108 -0.08617732 ...  1.0905851   0.29349384
 -0.19236536]
000000049269.jpg
[ 0.20482793  0.18914391  0.7335551  ...  0.09595802 -0.03787289
 -0.9793558 ]
000000049759.jpg
[ 0.46139705 -0.22449438  0.24010205 ...  1.678325    0.6831169
  0.08614145]
000000049761.jpg
[ 1.1584085   0.9182204   0.35773325 ... -0.14704975 -0.7448735
 -0.9490097 ]
000000049810.jpg
[ 0.40353662  0.2971995   0.7737895  ...  1.1566854  -0.15975332
 -0.6461935 ]
000000050006.jpg
[ 0.60478264 -0.6587463  -1.1646771  ...  0.03545798  0.8771198
  0.3735618 ]
000000050145.jpg
[ 0.38237563  1.5755272  -0.34889793 ...  0.8687956  -0.5719359
 -0.19376251]
000000050149.jpg
[-0.48125428  1.4643376  -0.17484064 ... -0.6676972   0.0141312
 -0.20225966]
000000050165.jpg
[ 0.64726174  1.1726586   0.9241656  ...  0.71

[ 0.41616315 -0.20132592 -1.027145   ...  0.50299835  0.5105091
 -0.5671657 ]
000000058655.jpg
[-0.5400748   0.03166009 -0.6632242  ... -0.40221384  0.4182981
  0.93056005]
000000058705.jpg
[ 0.41162503  0.61523587 -0.27627236 ... -1.551563    0.06808674
 -0.8419454 ]
000000059044.jpg
[ 0.15611202 -0.65080136  0.37727877 ...  0.5563565   0.18286979
 -0.24700035]
000000059386.jpg
[ 1.2560563  -0.2748269   0.5924748  ...  0.46264723  0.48413315
 -0.634336  ]
000000059598.jpg
[-0.56786865 -0.36861527 -0.02859296 ...  0.57516146  0.17689858
  0.06025558]
000000059635.jpg
[ 0.23274636 -0.41616392 -0.79480207 ...  0.00380916  1.2295732
  0.625586  ]
000000059920.jpg
[-0.6439399   1.5030817  -1.029602   ...  0.29381382  1.5484737
 -1.1618901 ]
000000060052.jpg
[-0.67982715  0.94146764  0.02611349 ...  0.6299998   0.46302873
  0.38565668]
000000060090.jpg
[ 0.44291407  1.7387931  -1.1896334  ... -0.2573809   0.18205151
 -0.41101822]
000000060102.jpg
[ 0.97394276 -0.6473388   0.1220756  ...  0.

[ 0.8831735  -0.4089733   0.45501912 ... -0.29412597  0.06555772
 -0.2292895 ]
000000068833.jpg
[-0.47097674  0.8309922  -0.24650247 ...  0.36147752  0.96858466
  0.10009448]
000000068933.jpg
[ 1.1590781   0.6298515   0.11533394 ... -0.37793428 -1.2381728
  0.18196794]
000000069106.jpg
[ 0.7008501   0.27964813  0.14929517 ...  0.43575543 -1.0498852
 -0.6199867 ]
000000069138.jpg
[ 1.7297211   0.03231424 -1.4841878  ... -0.6224359  -1.0288678
 -0.7699495 ]
000000069213.jpg
[ 0.7352661   0.9316628   0.41925824 ... -0.6740737   0.41169578
 -0.21508612]
000000069224.jpg
[ 0.6842697   0.48343518 -0.18354872 ...  0.453244   -0.88854265
 -0.60874254]
000000069356.jpg
[ 1.6239697   1.2304144  -1.3758085  ... -0.35758123  0.12433562
 -0.01367475]
000000069795.jpg
[ 0.32473567 -0.4661414   1.3287754  ...  1.3587325   1.6758988
 -0.07901122]
000000070048.jpg
[ 0.67909116  1.1291491  -0.6330251  ...  0.5969795   0.04204812
  0.18327403]
000000070158.jpg
[ 0.58033127  0.3372783  -0.00713644 ...  0.

[ 0.07810142  0.5224381   0.10793912 ...  0.6167553  -0.1128303
 -0.5593465 ]
000000080671.jpg
[-0.02141062 -0.34070987 -1.0713571  ... -0.02609657  0.2047865
 -0.42008775]
000000080932.jpg
[-0.01762957  0.22825956  0.50068486 ...  0.7647897  -0.06471799
 -0.07855769]
000000080949.jpg
[ 0.670138   -0.9249056   0.24376798 ...  0.5676325  -0.1360322
 -1.0425448 ]
000000081061.jpg
[ 0.24260184  0.44147056 -0.3407507  ...  0.4466242  -0.36205742
 -0.15011656]
000000081394.jpg
[ 1.2821841   0.5313011  -1.0352442  ... -0.2199583   1.0230465
 -0.28935468]
000000081594.jpg
[-0.65232563  0.01599904 -0.57914746 ...  0.08991444  0.77645177
 -1.1288779 ]
000000081738.jpg
[-3.3068845e-01  3.2073528e-02 -4.1434622e-01 ...  1.0810931e+00
  1.7746389e+00 -8.9267187e-04]
000000081766.jpg
[ 0.405526   -1.2091825   0.485034   ... -0.11708142 -0.14504237
  0.1364617 ]
000000081988.jpg
[-0.67647564 -0.64405394  0.26518512 ...  1.4117608   0.7291827
 -0.24059066]
000000082085.jpg
[-0.59876186  1.9353272   0

[ 0.90144867  1.4389725  -0.43512955 ...  0.15471385 -0.32662082
 -0.8953898 ]
000000090208.jpg
[ 0.5393465  -0.3251524   0.05630285 ...  0.18056586  0.38327575
  0.6841081 ]
000000090284.jpg
[ 0.0169966   0.41236788 -0.07577647 ...  0.26447034  0.6234555
 -0.9483589 ]
000000090631.jpg
[ 0.6311187   0.24729371 -0.27675554 ...  0.60554487  0.5975907
 -0.6631687 ]
000000090891.jpg
[ 0.6355148   1.2136751  -0.55653137 ... -0.3288181  -0.60728127
 -0.37435034]
000000090956.jpg
[ 0.04748869 -0.14190336 -1.4316021  ...  0.76088095  1.5760825
 -0.42310897]
000000091406.jpg
[-0.2760124   0.4272961   0.45444646 ...  0.8288098   0.74272996
  0.3975498 ]
000000091495.jpg
[-0.16697165  0.13682562 -0.19340275 ...  0.5606478   1.1434913
 -0.73066455]
000000091500.jpg
[-0.20953001  0.2508187   0.75588596 ...  0.3309888  -0.67988914
  0.70786166]
000000091615.jpg
[ 0.28363052  0.48637185 -0.8235882  ...  0.42330053  0.20657462
 -0.91045225]
000000091619.jpg
[ 0.9955015   0.30518216 -0.10572027 ...  1.

[ 0.8195968  -0.2594528   0.22198999 ... -0.5515708   0.32908586
  0.7265447 ]
000000101022.jpg
[ 0.12760936 -0.37772155 -1.5353521  ...  0.51206285  1.0476876
 -0.6908249 ]
000000101068.jpg
[-0.15204646  0.44723424 -0.7469455  ...  0.554036    0.7315879
 -1.2651633 ]
000000101420.jpg
[ 0.34951794  0.2787699   0.41632387 ...  0.587132   -0.01735828
 -0.83920145]
000000101762.jpg
[-0.7373064  0.5605925  1.1399236 ...  1.0993581 -0.2019025 -1.1025224]
000000101780.jpg
[ 1.7223033   0.38451344  0.3878278  ...  0.31501547 -0.81644005
 -0.54917747]
000000101787.jpg
[ 0.7827269   0.40013674 -0.9062437  ...  0.82996976  0.96108115
  0.11726597]
000000101884.jpg
[-0.22279058 -0.36170143 -0.7210911  ... -0.01176363 -0.00911494
  1.607051  ]
000000102331.jpg
[-0.06557089 -0.79156405 -0.23714751 ... -0.05594795 -0.79145265
 -1.1379573 ]
000000102356.jpg
[-0.84691554  0.60263234  0.10584562 ... -1.5060028  -0.590053
 -1.112232  ]
000000102411.jpg
[-0.1793631  -0.19803627  0.07660429 ... -0.6503988

[-0.27863523 -0.65994227  0.5992587  ... -0.02953935  0.34688652
 -1.3646207 ]
000000112298.jpg
[-0.18337494  0.06721628 -0.4197762  ...  0.01204862  0.5686808
  0.26992837]
000000112378.jpg
[-0.03382434 -0.0591738   0.20411932 ...  0.7786823  -0.03535037
  0.57883203]
000000112626.jpg
[-0.3675616   0.55795944 -0.51086015 ...  0.777911    0.69568557
 -0.920604  ]
000000112634.jpg
[ 1.4284415   1.3629833   0.87977445 ...  0.25027648  0.7151507
 -1.3926312 ]
000000112798.jpg
[ 1.1920602  -0.5769975   0.31705144 ...  1.0289608  -0.25795117
 -1.2499355 ]
000000112997.jpg
[-1.0780728   1.536531   -0.20490511 ...  1.0346642   1.5739601
  0.03262119]
000000113051.jpg
[ 0.04940066  0.5385981  -0.7522399  ...  1.7986884   0.16172756
 -0.1461796 ]
000000113235.jpg
[ 0.72346145  1.275851    1.7693607  ...  0.82989955 -0.0730391
  0.71922624]
000000113354.jpg
[ 0.9626637   0.19272384  0.67748636 ...  0.604155   -0.81676257
 -1.0591413 ]
000000113403.jpg
[ 0.24591683 -0.495238   -0.06363701 ...  1.

[ 0.7000869   1.0402684   0.04669416 ... -0.7953485   0.88790613
  0.3138188 ]
000000123480.jpg
[-0.53310084 -0.01052557  0.26225534 ...  0.8787342   0.3292632
 -0.18563454]
000000123585.jpg
[ 0.26083648  0.59869826  0.8586004  ...  0.4558073  -0.6587836
 -0.61177796]
000000123633.jpg
[ 0.28304005 -0.4834078   0.08862424 ...  0.4986762  -0.29304984
 -0.15079296]
000000124277.jpg
[-0.33395356  0.12980627  0.18882616 ...  0.36464676  0.27263948
 -1.1574777 ]
000000124442.jpg
[-0.35743916 -0.4274001  -0.72971445 ...  1.414996    0.28227472
 -0.5785779 ]
000000124636.jpg
[ 1.2382722   1.4185857   0.33793366 ... -0.02053459  0.9861651
 -0.2244449 ]
000000124659.jpg
[-0.28212312 -0.333111    0.62293553 ...  0.888823    0.01657833
 -0.44345295]
000000124798.jpg
[ 1.0660791   0.41886336 -0.31159374 ...  1.278467   -0.61055976
  0.9326219 ]
000000124975.jpg
[ 1.2517055   0.67958355  0.41667116 ...  0.6945726  -0.49186113
 -1.5064044 ]
000000125062.jpg
[ 0.57212687 -0.49898     0.0449977  ...  0

[ 0.8449384   0.03168301 -0.36807346 ... -0.03368359 -0.62646437
 -0.43974665]
000000132544.jpg
[ 0.3547243   0.4471583  -0.8491894  ... -0.04286096  0.6665241
 -0.11825447]
000000132587.jpg
[ 0.12056829 -1.244486    0.3593604  ... -0.29636693  0.21029662
  0.55103064]
000000132622.jpg
[-0.29689774  0.26450232  1.0861572  ...  0.5031491  -0.25145504
  0.44860998]
000000132703.jpg
[ 0.18979764 -1.2192916   0.79137385 ... -0.6043472   1.5361239
  0.6296892 ]
000000132796.jpg
[ 1.3214396   0.38290647 -0.31595266 ...  1.12711    -0.18400957
 -1.1385857 ]
000000132931.jpg
[ 1.0277752   0.02206255  0.80361503 ...  0.2027712   0.59497124
 -0.0721172 ]
000000133000.jpg
[ 1.3902569   0.47009027 -1.182209   ...  0.3442447  -0.73907906
 -0.51725405]
000000133087.jpg
[ 0.9142691  -0.5910631  -0.5843745  ...  0.376957   -1.300027
 -0.31335598]
000000133233.jpg
[-0.20388278  0.31442288  0.02433231 ...  0.49849418  0.47327352
 -0.2392096 ]
000000133244.jpg
[-0.8678334   0.5520751  -0.2541615  ...  1.

[ 1.4173706   0.7764114  -1.0791354  ...  1.059965    0.18583803
 -1.9275037 ]
000000142472.jpg
[-0.1919134   0.16745192 -1.3917147  ...  0.0361958  -0.05842481
 -0.00891038]
000000142585.jpg
[ 1.8727556  1.7808659 -1.4923517 ... -0.5027682 -0.4586055 -1.2875285]
000000142620.jpg
[-0.46452916 -0.2598379   0.7031328  ...  0.503606   -0.37922445
 -0.23693022]
000000142790.jpg
[ 0.39956376 -0.5351992   0.1684976  ... -0.36406976  0.6657893
 -0.34716022]
000000142971.jpg
[-0.25970942 -0.88868785  0.1674936  ...  0.84026855 -0.42445654
 -0.4823219 ]
000000143068.jpg
[-0.45723164 -0.9820757  -0.9148178  ...  0.26319948  0.33017725
 -0.07617882]
000000143556.jpg
[-1.124456    0.5232579  -0.8505515  ...  0.36308792 -0.5889992
 -0.83832586]
000000143572.jpg
[-0.7940633   0.2949217  -1.0854911  ...  0.3848406  -0.09327118
 -0.29689604]
000000143931.jpg
[ 0.2651397  -0.48108873  0.13969924 ...  0.257966    0.5909299
 -0.8429205 ]
000000143961.jpg
[ 0.4460032  -0.00838324 -0.13924193 ... -0.591755

[ 1.7195096   0.30535766  1.0113102  ...  0.16046274 -0.62632006
 -1.5238624 ]
000000153011.jpg
[ 0.42812383  0.9203617   0.83318084 ... -0.25428113 -0.6984422
 -0.05453942]
000000153217.jpg
[-0.668465   -0.01750281  1.0057302  ...  0.05182527 -0.9223829
 -0.8720304 ]
000000153229.jpg
[ 0.3299926  -0.40823165 -0.14740229 ...  0.82772595  1.037284
 -0.5625928 ]
000000153299.jpg
[ 1.564962    0.7559775   0.9351484  ... -0.09473587 -0.3522008
 -1.4114031 ]
000000153343.jpg
[ 0.37214786  0.7855147  -0.6673651  ... -0.8463946   0.73458827
 -0.41689324]
000000153510.jpg
[ 0.7891877   2.4736946   0.6028904  ... -0.02446935 -0.64964634
  0.34320927]
000000153527.jpg
[-0.01124514  0.23675096  0.13978474 ...  0.3253208  -0.11334163
  0.02506755]
000000153529.jpg
[-0.35250843  0.882363    0.04240832 ... -0.25760907 -0.5511431
 -1.1925281 ]
000000153568.jpg
[ 1.0297693  -0.00864284 -0.19905709 ...  0.38285694  0.18067203
 -0.6511574 ]
000000153632.jpg
[-1.233948   -0.564533    0.4251524  ...  0.29

[ 0.22516459  0.03673668  0.09602986 ...  0.07594166  0.05630298
 -0.5000197 ]
000000161879.jpg
[ 0.63370216 -0.7154969   0.7444301  ...  0.02866793  0.67278105
  0.3121214 ]
000000161925.jpg
[-0.38228297  0.85735685  0.4873434  ...  0.43297178 -0.1238439
 -0.65731764]
000000161978.jpg
[ 0.20037587 -1.3880363   0.4950785  ... -0.58587044  0.2730634
  0.696418  ]
000000162035.jpg
[ 0.7000569   0.07605688 -0.1615016  ...  0.4985691   0.5364956
 -0.02759277]
000000162092.jpg
[-0.19547768 -0.4305421  -0.94564044 ... -0.2338638   0.6342372
  0.6226158 ]
000000162130.jpg
[ 0.820905   -1.2991585   0.39148635 ...  0.3396824   0.29613325
 -0.11492962]
000000162366.jpg
[ 0.03532582 -0.23195028 -0.23963407 ...  1.0521055  -0.00765091
  0.44715974]
000000162415.jpg
[-0.8388654  -1.0737903   0.3833792  ...  0.2496143  -0.10546632
  0.4149069 ]
000000162543.jpg
[ 0.1464932   0.6056297  -0.6803793  ...  0.7224461   0.48328966
 -0.23464116]
000000162581.jpg
[-0.7201947  -0.44087496  0.04694107 ...  0.

[ 0.35642183  0.37201434 -0.6673642  ... -0.01869958 -0.46663684
 -0.9076133 ]
000000170595.jpg
[-0.2425113   0.09707632 -0.3662798  ... -0.5321443  -0.2532705
 -1.2578366 ]
000000170613.jpg
[ 0.23342365 -1.1410308  -0.17290658 ...  0.00588394  0.93371695
 -0.47976774]
000000170670.jpg
[-0.1154874  -0.6542459  -0.21040176 ...  0.36073476  0.72062284
  0.01809881]
000000170739.jpg
[ 0.9821168   1.2756499  -0.80919445 ...  0.24478555 -0.34830776
 -0.87486243]
000000170893.jpg
[-0.03130533  0.05992911  0.2790283  ...  0.2141554   0.6538895
 -0.3674054 ]
000000170955.jpg
[ 0.20110731 -0.33300123  0.04163867 ...  0.41992086  0.20401873
 -0.9817606 ]
000000171050.jpg
[ 0.12728186  0.70920163  0.10266139 ...  0.0350328   0.36511627
 -0.6952983 ]
000000171190.jpg
[-0.93086034 -0.07921692  0.02434987 ...  0.71514344  0.80562687
  0.21763332]
000000171298.jpg
[ 0.39954045  0.8185416  -1.4709718  ...  0.44326565  0.72996914
 -0.5274754 ]
000000171382.jpg
[ 0.6230738  -1.1821748  -0.02791637 ... -

[-0.03199655  0.6764735  -0.48124245 ...  1.067008    0.65151083
 -0.28786412]
000000179392.jpg
[-0.26580918  0.36005938  1.0963248  ...  0.53103507 -1.2554557
 -0.7512593 ]
000000179487.jpg
[-0.25094816  0.7688768  -1.3552841  ... -0.3334172   1.2977182
  0.6812734 ]
000000179642.jpg
[-1.0128689   0.0876427  -1.2320416  ...  0.4069159   0.38811824
  0.41894564]
000000179653.jpg
[0.08224899 1.3867468  0.06625741 ... 0.16679695 1.227201   0.31631875]
000000179765.jpg
[-1.0841434   0.40595847  0.9237943  ... -0.06657901 -0.07309896
 -0.8871318 ]
000000179898.jpg
[0.04751204 0.55639863 1.5137461  ... 0.01715517 1.3254862  0.39999008]
000000180011.jpg
[ 0.87683815  0.24835245  0.9625339  ...  0.64317673 -0.27502957
 -0.7888812 ]
000000180101.jpg
[-0.32606944 -0.33062476  0.09406004 ...  0.89898384  0.15108621
  0.43547434]
000000180135.jpg
[-0.9747724  -0.351561   -0.25574175 ...  0.00137004  0.2711761
  0.3128677 ]
000000180188.jpg
[-0.5249658   1.0720352  -0.09540449 ...  0.13923502 -0.1

[ 0.07854097  0.27248654 -0.11346935 ... -0.9068495   1.6689527
  0.54348576]
000000187362.jpg
[-0.24603233 -1.7312065  -0.9807171  ...  0.44300312  0.18976034
 -0.31376705]
000000187513.jpg
[ 0.19287314  1.806303   -0.94322634 ... -0.77282834  1.1655937
 -1.0551608 ]
000000187585.jpg
[-0.13211088 -0.0257302   0.60777235 ...  0.7937506   0.69446516
  0.10073795]
000000187734.jpg
[-0.22576614 -0.8519398   0.346437   ...  1.146557    0.05981826
  0.18312106]
000000187745.jpg
[ 0.14824207 -0.93353826  0.20549728 ... -0.6231804   0.5813205
  0.21882595]
000000187990.jpg
[ 0.59990734 -1.3377204   1.150953   ...  0.15499632  1.0747731
  0.292649  ]
000000188296.jpg
[-0.47716904  0.05625543 -0.1731497  ...  0.46376765  0.3915364
  0.22784105]
000000188439.jpg
[ 1.3809971   0.60490036 -1.0955616  ...  0.15060192 -0.00635766
 -0.35919687]
000000188465.jpg
[ 0.10858011 -0.43678093  0.48167744 ...  1.4274821  -0.5249041
 -0.27440992]
000000188592.jpg
[-0.6899858  -1.3518139   0.26539192 ...  0.15

[ 0.7145532  -1.1411407   0.04793196 ...  2.157951    1.0089699
 -0.13307944]
000000197004.jpg
[ 0.8022921   1.3538985   0.07841935 ... -0.2230119   0.8636016
 -0.36757025]
000000197022.jpg
[0.8004929  0.4585256  0.68840647 ... 1.3924123  1.108086   0.5411359 ]
000000197388.jpg
[ 0.5818993   0.2564294  -0.44136307 ...  0.12686664  0.00490287
 -1.1729314 ]
000000197528.jpg
[ 0.24914353  0.27394256  0.865439   ...  0.15152459 -0.85902256
 -0.80584794]
000000197658.jpg
[-0.05583509 -0.2761241   0.96577907 ... -0.36274296  0.6015288
 -1.5863463 ]
000000197796.jpg
[-0.5014511  1.3018415 -1.1889102 ...  0.1929017  0.7181173 -0.8237555]
000000197870.jpg
[ 0.5462781   0.10978935  1.1828847  ... -0.31005663 -0.689076
 -0.03262364]
000000198489.jpg
[-0.7086946  -0.54630977  1.1218691  ...  0.14089124  1.4679798
 -0.6725566 ]
000000198510.jpg
[ 0.8319271   0.41614527  0.5290989  ...  0.2035647  -0.29713157
 -1.4447587 ]
000000198641.jpg
[ 1.3070405   0.6054926   0.6117678  ... -0.31994003 -0.7691

[ 0.6251615  -0.5229717   0.83521575 ...  0.95461273 -0.73144126
  0.6414719 ]
000000208423.jpg
[ 0.45401412 -0.43529868  0.11492395 ... -0.36681384 -0.4999823
  0.15365757]
000000208901.jpg
[ 0.28772086 -0.49989718 -0.10853454 ...  0.38705447  0.59469575
 -0.2730442 ]
000000209142.jpg
[ 0.4155181  -0.4890598   0.04591185 ...  0.15510261  1.0616472
  0.4323685 ]
000000209222.jpg
[ 1.3100846  -1.2278306   0.7554987  ...  0.04748661 -0.91907954
  0.94512254]
000000209530.jpg
[-0.19870077  0.5237132  -0.15881813 ...  1.2684478  -0.00848696
 -0.53827405]
000000209613.jpg
[ 0.49025923  0.5720899   0.7735606  ... -0.31950498  1.1375736
 -1.2152756 ]
000000209747.jpg
[ 0.2360839   0.53672826 -0.5794893  ...  0.2548602   0.6967249
 -1.2943907 ]
000000209753.jpg
[ 0.48391318  0.8699134  -0.17564246 ... -0.3788798   0.36503482
  0.5769993 ]
000000209757.jpg
[ 1.0046668  -1.345791    0.5366052  ... -0.25457662 -0.18935262
 -0.34900233]
000000209829.jpg
[ 0.33919412 -0.25947818 -0.07315172 ...  0.

[-0.22302659  0.48286375 -1.3415763  ...  0.6697487  -0.36331263
 -0.49392116]
000000218249.jpg
[ 1.5894579   0.12397464  0.6052903  ...  0.69390714 -0.3968685
 -0.23755121]
000000218362.jpg
[ 0.12660456  0.6027847  -0.10210844 ... -0.50922155 -0.26304746
 -0.9781887 ]
000000218424.jpg
[ 1.2209198   0.72874653 -0.0920562  ...  0.53253955 -0.48728853
 -0.8881367 ]
000000218439.jpg
[-0.68599427 -0.5514779   0.63566273 ...  0.25526404 -0.9564609
 -0.56357116]
000000218997.jpg
[ 0.23138364  0.01329914  0.69978    ... -0.38457847 -0.7266795
 -0.7502742 ]
000000219271.jpg
[ 0.7351774   1.2098624   0.11965951 ...  0.9880964   1.7828574
 -0.7414247 ]
000000219283.jpg
[ 0.12631041  0.637818   -0.06430411 ...  0.08751577  0.24502231
  1.3160115 ]
000000219440.jpg
[ 1.0998418   1.2598354   0.3729069  ... -0.5967117   1.2381577
  0.02090058]
000000219485.jpg
[ 0.18051422 -0.4233085   0.65717524 ...  0.41490865  0.14540172
  0.39419487]
000000219578.jpg
[ 0.06089486  0.24634725  0.5841159  ...  0.2

[ 0.20649387 -0.6535335  -0.07478888 ...  0.6387855  -1.326369
 -0.19618697]
000000227985.jpg
[ 0.13920128  0.48066294 -0.85448706 ... -0.46102017  0.7614097
 -0.5423068 ]
000000228144.jpg
[ 0.9389675   0.65264934 -0.1299507  ...  1.0742792   0.22399834
 -0.25789773]
000000228214.jpg
[ 0.37738627 -0.08443432 -0.58322346 ... -0.51061255  0.55810624
  0.19498788]
000000228436.jpg
[ 0.958899    0.25431958  0.9644158  ...  1.1823734  -0.3828191
 -0.8123537 ]
000000228771.jpg
[ 0.533976    0.39565986  0.44206655 ...  0.29125524  1.3778065
 -0.25735918]
000000228942.jpg
[-0.7422566  -0.12118512 -0.3897597  ... -0.04184289 -1.1445422
  0.05831667]
000000228981.jpg
[-0.5091201   0.7356987   0.00933046 ...  0.5748705   0.6740049
 -0.05971622]
000000229111.jpg
[-0.4222117  -0.04999892  0.8094945  ...  0.6574648  -0.4140243
  0.36773503]
000000229216.jpg
[ 0.89530677  0.06690609  0.39394227 ...  0.07328235  0.9476694
 -0.08666559]
000000229221.jpg
[ 1.3911732   0.7686232   0.2955028  ... -0.67966

[ 0.15515338 -0.14713313  0.90397567 ... -0.8690275  -0.22020191
 -0.71589303]
000000236845.jpg
[ 0.34905985 -0.98488975 -0.8176577  ...  0.7575501  -0.3950296
  0.17698601]
000000236914.jpg
[ 0.15422137  0.09124614  0.7337916  ... -0.5424385   0.82899535
  0.9243846 ]
000000237071.jpg
[-0.20209269 -0.2862888   0.78500754 ...  0.8841783   1.1566014
 -0.66641736]
000000237118.jpg
[-0.43008912 -0.85676396 -1.4877305  ... -0.5923853  -0.5808765
 -0.41042596]
000000237316.jpg
[ 0.02548626  1.7226135  -1.1432308  ... -0.8244587   1.3612918
 -1.2654386 ]
000000237517.jpg
[-0.04989731  0.94003993 -0.43739673 ...  0.58457786  0.8864212
 -0.725532  ]
000000237864.jpg
[ 1.0846652   0.1944212  -0.33351904 ... -0.20299233  0.38847503
 -1.4016731 ]
000000237928.jpg
[ 0.03794282  0.46814263 -0.557347   ...  0.68388927 -0.02623852
 -0.6482004 ]
000000237984.jpg
[ 0.44800174 -0.16519122  0.22634028 ...  0.8449822  -0.15645099
  0.24524663]
000000238013.jpg
[-0.2857749  -0.48966363  0.4128092  ...  0.1

[ 0.7002236  -0.22081327  1.0699227  ...  0.57709414  0.23809657
 -0.15151201]
000000248334.jpg
[-0.10053922  0.16983081 -0.4726837  ...  0.879486   -0.3938116
  0.38426206]
000000248400.jpg
[ 0.152032    0.01405672 -0.00621813 ...  1.3308032  -0.48563898
 -0.08469289]
000000248616.jpg
[-0.9157065  -0.6515234  -0.03033654 ...  0.59035355  0.907758
 -0.10665964]
000000248631.jpg
[ 0.1867952   0.71155804  0.6730126  ...  0.4247002   0.6531501
 -0.20576148]
000000248752.jpg
[-0.11541831 -0.13183552  0.08746631 ... -0.38354042  0.14166394
 -0.76253223]
000000248810.jpg
[ 0.98629653  0.6498919   0.28147    ...  1.1541864   0.3056263
 -0.992789  ]
000000248980.jpg
[ 0.8376758   0.15660754  0.05831936 ... -0.05462093  1.3822789
 -0.5989296 ]
000000249025.jpg
[ 0.6111442   1.1255771  -0.11794767 ... -0.06059668  0.7194901
 -0.47995052]
000000249129.jpg
[-0.30724707 -0.69944185 -0.28660756 ...  0.26364043 -0.15889324
  0.15935175]
000000249180.jpg
[ 1.0922384   0.00806204 -0.10388015 ...  0.114

[ 0.2451821   0.4128634   0.8850434  ...  1.0860432  -0.47074026
  0.42446288]
000000259625.jpg
[ 1.3191608  0.7215633  0.5672436 ...  1.1618644  1.2793727 -0.6678915]
000000259640.jpg
[ 0.86111504  1.7679716   0.6772138  ...  0.64266545 -0.21772723
 -0.5729623 ]
000000259690.jpg
[-0.6276977  -0.09825625 -0.27474135 ...  0.48810208 -1.1085302
 -2.045862  ]
000000259830.jpg
[ 0.61915433 -0.5110466  -1.6542038  ... -0.01535653  0.9729775
 -0.08059402]
000000259854.jpg
[ 0.9618794   0.43899146 -0.02411897 ... -0.5020683   0.2915136
 -0.9151458 ]
000000260105.jpg
[ 0.45642227  1.2800477   0.19706503 ...  0.18675536  0.25735945
 -2.0150435 ]
000000260106.jpg
[-0.59691256  0.6914133  -1.2144825  ... -0.86124957 -0.62575847
 -1.1434176 ]
000000260261.jpg
[ 0.7635682   0.66363764 -0.37910682 ... -0.8456602   0.36743277
 -0.42764336]
000000260266.jpg
[ 1.3342081  -0.21349518 -0.5901466  ... -0.1931119  -0.90268254
  0.08746367]
000000260470.jpg
[ 0.08190893  0.36393747  0.04952336 ...  1.276437

[ 0.7342219   0.6649723   0.38653034 ...  0.20046733  0.42515418
 -1.8337444 ]
000000269866.jpg
[-0.59549904  0.04695135 -0.27617776 ... -0.01893355 -0.31691822
  0.07239196]
000000269932.jpg
[ 1.1416814  -0.8391819   1.3971633  ... -0.850412   -0.06941801
 -0.48259622]
000000269942.jpg
[ 1.3509852   0.07468819 -0.67462575 ... -0.28516045 -0.56081134
 -2.186703  ]
000000270066.jpg
[-0.65214866  1.2871574   0.46727225 ... -0.45939472 -0.62403834
 -0.6008827 ]
000000270122.jpg
[ 0.6267208  -1.1509582  -0.20665966 ...  0.10779218  1.1336831
 -0.8130414 ]
000000270244.jpg
[ 0.6862189   0.62239355  0.25369558 ...  0.02124146 -0.55435926
 -0.35322315]
000000270297.jpg
[ 1.1855631   1.0425076  -1.0766612  ... -0.05356851  0.10541797
 -1.0966877 ]
000000270386.jpg
[ 0.17405276 -1.1437026   0.67136836 ...  0.7783478   1.4787446
  0.4057284 ]
000000270402.jpg
[ 0.85015804  0.94821846  0.17444663 ...  0.93027604 -0.96215653
 -0.7172581 ]
000000270474.jpg
[ 0.20592783  0.20357852  0.48001516 ... -

[ 0.14821821 -0.4497503  -0.736598   ...  1.6664776  -0.0463288
 -0.18039596]
000000280779.jpg
[ 0.33935022  0.00447753 -0.22784361 ... -0.58306634  0.24385208
 -1.2203826 ]
000000280891.jpg
[ 0.3275169   0.7467052   0.11428367 ...  0.93131864 -0.14845282
  1.025748  ]
000000280918.jpg
[ 0.50227123  0.760206    0.7553858  ...  0.5725495   0.61058426
 -0.19255273]
000000280930.jpg
[-0.3036468  -0.01684848  0.88320905 ...  1.7908231   0.3053047
  0.8864526 ]
000000281032.jpg
[ 0.15556651 -0.2328403   0.15340571 ...  0.37471765 -0.7038366
 -0.03745773]
000000281179.jpg
[ 0.21857958 -0.33457643 -0.00670595 ... -0.7198954  -0.55844355
  0.06719818]
000000281409.jpg
[ 0.78510183 -0.53219366 -0.10512506 ... -0.55682576  0.19964091
 -0.05662095]
000000281414.jpg
[ 0.55767745  0.28411105 -0.05869652 ...  0.12617782  0.779802
  0.33167645]
000000281447.jpg
[-0.57824343  0.9631094   0.77479005 ...  0.47025877 -1.0253636
 -0.44573683]
000000281687.jpg
[-0.02765581  0.05756807 -0.43844688 ...  0.27

[ 0.6583605   0.6701833   0.25151876 ...  0.85970235 -0.07383329
 -0.25723073]
000000289702.jpg
[-0.27008647  0.85984945  0.9462018  ... -1.0217698   0.48987898
 -0.33137226]
000000289741.jpg
[ 1.066548    0.16373903  0.26571488 ...  0.53714836 -0.45100588
 -0.19119903]
000000289938.jpg
[-0.26109543  0.50398874 -1.1614425  ... -0.22047314 -0.87406635
 -0.04291257]
000000289960.jpg
[ 0.09035189 -0.2900824   0.7543332  ...  0.14788468  0.6148007
  0.09601187]
000000289992.jpg
[-0.9466456   1.2893717  -0.60652816 ...  0.66815114  1.4834685
 -0.42009416]
000000290081.jpg
[ 1.0767885   0.47723895 -0.76768917 ... -0.73637235  0.41875455
 -0.14515726]
000000290163.jpg
[-0.14779946  0.8429684   1.6841115  ...  0.88973606  0.39372846
  0.09784022]
000000290179.jpg
[ 0.24195781 -0.07264215  0.55974114 ...  1.0347755  -0.41503522
 -0.5905597 ]
000000290248.jpg
[ 0.80207336 -0.31488588  0.6890841  ...  0.84567577  0.3609539
 -0.63042176]
000000290293.jpg
[-0.54634285  1.5719279   0.48479936 ...  1

[ 1.2791913   0.77102464  0.01293435 ... -0.46617815  1.131737
 -1.0520592 ]
000000297830.jpg
[-0.36032218 -0.6491326   0.05747989 ... -0.40578598  1.5899924
  0.17770348]
000000298251.jpg
[ 0.28705183 -0.35903472 -0.07523541 ... -0.62482    -0.02035839
 -0.8406135 ]
000000298396.jpg
[-0.07876295  0.3914471   0.21608897 ...  0.4429357   0.3405803
 -0.513133  ]
000000298697.jpg
[ 1.2813119   1.0331255  -0.03074929 ...  0.38951415 -0.68468237
 -0.20634265]
000000298738.jpg
[ 0.3037691   0.74812776 -0.23780864 ...  0.4812093   0.5199575
  0.0724167 ]
000000298904.jpg
[ 0.37412828 -0.05997562  0.20595784 ...  0.5654939   0.7652266
 -0.38378412]
000000298994.jpg
[-0.21254598  1.0582842   1.6926082  ...  1.1712679   0.07052153
  0.3550152 ]
000000299355.jpg
[ 0.63866436  0.08538783  0.57760507 ... -0.26925516 -0.11359169
  0.15331075]
000000299553.jpg
[ 0.10715985  1.3066205   0.29518282 ... -0.581568    0.25379226
 -1.0599998 ]
000000299609.jpg
[ 0.8615438   1.508333    0.6184319  ... -0.23

[-0.0809584   0.29061666  0.2695682  ... -0.01615906  1.1256348
 -0.6913955 ]
000000308799.jpg
[-0.06514858  1.359491    0.658004   ...  0.7649222  -0.22244278
 -0.7967928 ]
000000309173.jpg
[ 0.9490923   0.4787098  -0.3672616  ...  0.7457646   0.46775424
 -0.67254066]
000000309391.jpg
[ 0.78718245 -0.69900095 -0.28587258 ...  0.06299996 -0.49619463
  0.2639239 ]
000000309452.jpg
[ 0.39605352  1.0491815  -0.34409803 ... -1.101978    0.36840707
 -0.2457651 ]
000000309467.jpg
[ 0.3886189   0.757711   -0.2623767  ...  0.33359557  0.58021116
 -0.06805804]
000000309484.jpg
[-0.07855293 -0.8215121  -0.33516303 ...  0.11251983  0.08544712
 -0.8833533 ]
000000309495.jpg
[ 0.23496321  0.8981816  -0.2064319  ...  0.14966601  0.7917839
 -0.3912217 ]
000000309655.jpg
[-0.26146868  0.10979613 -0.79302835 ... -0.04834894  0.01687606
 -0.22666655]
000000309678.jpg
[0.5465523  0.01601446 0.5976401  ... 1.3455948  1.2940283  0.05105606]
000000309938.jpg
[-0.13721196 -0.5363972  -0.20061268 ...  0.81619

[-0.2208254   1.3626506  -0.87903655 ...  0.4167999   0.06466416
  0.23721199]
000000320232.jpg
[ 0.6572248  -0.6237609   0.14630601 ... -0.54994416  0.52881134
  0.64905095]
000000320425.jpg
[ 0.5285187   0.8234532   1.2521862  ...  1.1218574  -0.13552617
 -0.8358824 ]
000000320490.jpg
[-0.8345481  -0.33711597 -0.12584516 ... -0.48157272 -0.45156774
 -0.71047026]
000000320554.jpg
[-0.2945625  -0.37676919  0.21138945 ...  0.09491862  0.08169077
 -0.36869434]
000000320632.jpg
[ 1.3546352   0.38551587  0.07551987 ...  0.44454092 -0.4781105
 -0.66699   ]
000000320642.jpg
[-0.28217086 -0.69076836 -0.35449582 ... -0.39649534  0.71734643
  0.09837206]
000000320664.jpg
[ 1.35447     0.18808368  1.1894187  ...  0.3800104   0.38323385
 -0.4001117 ]
000000320696.jpg
[-0.11625127 -1.3992541   0.6307745  ... -0.30447417  0.9250472
 -0.6175873 ]
000000320706.jpg
[ 1.1457024   0.5325986  -1.1065258  ... -0.04559959 -0.12826292
  0.31611443]
000000320743.jpg
[ 0.76422226  0.94687414 -0.7695179  ...  

[0.04980534 1.4637253  0.25244159 ... 1.4901713  0.56795084 0.39397538]
000000329447.jpg
[ 1.1802807   0.41361186  0.65452266 ... -0.0189803   1.3057132
 -0.21352594]
000000329455.jpg
[0.30946738 0.23441266 1.2930025  ... 1.5014617  0.9236878  0.28581747]
000000329456.jpg
[ 0.59344304  0.46318537 -0.52953404 ... -0.66644764 -0.5990862
 -0.58375543]
000000329542.jpg
[-0.6273379   0.71603626 -0.79774415 ...  0.32065487 -0.37597027
 -0.29772303]
000000329614.jpg
[ 1.0293281  -0.12823288 -0.6422601  ...  0.09370224  1.0969054
 -0.7229121 ]
000000329827.jpg
[ 0.313386   -0.06434492 -0.7586225  ...  0.16328286  0.1310599
 -1.0898387 ]
000000330369.jpg
[-0.27915016  0.8231962  -0.6243311  ...  1.1487063  -0.40907124
  0.79234004]
000000330396.jpg
[-0.49317288 -0.2136118   0.80713004 ...  0.32301947 -1.2512413
 -0.66073376]
000000330554.jpg
[-0.3861679  -0.84062195 -0.09606455 ...  0.40334433 -0.6864126
  0.57220453]
000000330790.jpg
[ 0.5116827   0.68449444 -0.3654306  ...  0.94435537 -0.7594

[ 0.412905   -0.46034804  0.14539798 ...  0.8610454   0.04973976
  0.54863495]
000000340930.jpg
[ 0.18856683 -0.7574133  -0.7407432  ...  0.0800157   0.9492972
  0.36657658]
000000341058.jpg
[-0.10643911  1.4170417   0.03529424 ...  0.06937138 -0.57148516
 -0.5072975 ]
000000341094.jpg
[ 0.31721547 -0.32821533  0.05232736 ...  0.24049208 -0.38626835
 -0.05288058]
000000341196.jpg
[ 1.2171315  -0.63122106  0.44323057 ...  0.03304309  0.49816662
 -0.00507655]
000000341469.jpg
[-0.6262366   0.24034695  0.15075257 ... -0.05870346  0.324193
 -0.9648309 ]
000000341681.jpg
[-0.69378644 -0.5881953   0.2877432  ...  1.2531557   0.38196924
 -1.3564012 ]
000000341719.jpg
[ 0.5244878  -0.22676231 -0.43641278 ...  0.52729785  0.66203785
 -0.27747804]
000000341828.jpg
[ 0.45126027 -0.05077078  0.24898916 ... -0.24086592  0.24664256
  0.25315028]
000000341921.jpg
[ 0.23377922 -1.1653652   0.6620871  ...  0.17055614  0.18478149
 -0.13178149]
000000341973.jpg
[-0.0605583   0.7769565  -0.63625616 ... -0

[ 0.5513456   1.3482018   0.35698432 ...  1.5073133  -0.70740926
  1.005802  ]
000000350003.jpg
[ 0.466748   -1.1272686  -1.29805    ...  0.17518437 -0.6041576
 -0.13756837]
000000350019.jpg
[-0.3279594  -0.46140683  0.31459334 ...  0.5407867   0.43481314
 -0.04341643]
000000350023.jpg
[ 0.9112695  -0.4005309   0.43530798 ...  0.5235106   0.26898327
  0.6640936 ]
000000350054.jpg
[ 0.532299   -0.84955853  1.0883443  ... -0.70797634 -1.1381347
  0.08473124]
000000350122.jpg
[ 0.5317087   1.2659409   0.8864784  ...  0.9833734  -0.02659298
 -0.38456511]
000000350148.jpg
[-0.42263505  0.11302821 -0.62019086 ... -0.11511482  0.41529304
 -0.24080352]
000000350388.jpg
[ 0.580308   -0.1063711   0.26687014 ...  0.13253178  0.47658613
  0.27987278]
000000350405.jpg
[ 0.46488371 -0.76770794 -0.05396559 ... -0.50625575  0.9235533
 -0.39467493]
000000350488.jpg
[ 1.1506455   0.7311806   0.15071519 ...  0.6468227  -0.63325834
 -0.7847761 ]
000000350607.jpg
[-2.7788678e-01 -4.5170460e-02 -3.0389902e-

[ 1.1473842   0.1985942   0.4605334  ...  0.09357995 -0.38725182
 -0.37209895]
000000359833.jpg
[ 0.24044462 -0.24573961  1.3248329  ... -0.5069454  -0.27813005
  0.49542788]
000000359855.jpg
[-0.02753153  0.5156704   0.00182132 ...  1.2930601  -0.84908074
 -0.49334309]
000000359937.jpg
[0.12284442 0.5654599  0.3196376  ... 1.1038     1.4419088  0.30308077]
000000360097.jpg
[-0.35177937  0.697371   -0.6796535  ... -0.87302417 -0.27342752
 -0.09798606]
000000360137.jpg
[ 0.7101977   0.49018747 -0.95138335 ...  0.17689593  0.8711005
 -1.0054362 ]
000000360325.jpg
[ 0.46232283  1.7266897   1.2231308  ... -0.838414    1.4220114
 -0.60315096]
000000360393.jpg
[0.66713965 0.8798058  1.3351339  ... 1.7863953  0.9290072  0.26144496]
000000360564.jpg
[-0.24018501  1.0322561  -1.165938   ...  0.6219793   1.354963
  0.5254314 ]
000000360661.jpg
[-1.270021    0.20852214  0.06516101 ...  0.09675262 -0.47295487
 -1.0236819 ]
000000360943.jpg
[-0.17278282 -0.3055529   0.2150906  ...  0.07941692  0.89

[-0.03036724  0.40980387  0.5714539  ...  0.21504188 -0.7511381
 -1.5287902 ]
000000369310.jpg
[-0.37298906  1.2010046   1.2369876  ...  0.5023188  -0.00797901
  0.44404012]
000000369323.jpg
[ 0.35006663  1.0620604  -0.01919201 ...  0.00411962  0.11263208
  0.18438244]
000000369370.jpg
[ 0.4262074  -0.6739157  -0.9653482  ... -0.64686984 -0.11982188
  0.41564193]
000000369442.jpg
[ 1.3798126  -0.10668051 -0.0442678  ...  0.29173377  0.5606037
  0.14981864]
000000369503.jpg
[ 0.22454125  0.7314979  -0.56276244 ... -0.9025419   0.3852624
  0.65816814]
000000369541.jpg
[-0.924219   -0.5135089   0.6184043  ...  0.00630435  0.62763005
 -1.7407702 ]
000000369675.jpg
[ 0.06106722  0.98544914  0.51629436 ...  0.10487457  0.6400806
 -0.1303218 ]
000000369751.jpg
[ 0.75467557 -0.03370549 -0.6071345  ...  0.20973517 -1.0019407
 -0.07615536]
000000369757.jpg
[ 0.5522447   1.0075254   0.72469324 ...  1.1061726   0.93228686
 -0.42948994]
000000369771.jpg
[ 0.17052181  0.07476081  0.7852794  ... -0.3

[ 0.37927634  0.8916986  -2.1403234  ... -0.41719118 -1.2346524
 -0.18615307]
000000377946.jpg
[-0.6291558   0.5290503   0.358298   ... -0.5404662  -0.23310187
 -0.30803412]
000000378099.jpg
[ 0.9279115  -0.2732656   0.42575103 ... -0.85353106 -0.7797643
  0.25635424]
000000378116.jpg
[-0.38313493 -0.8311764  -0.17597236 ...  0.09610675  0.4990002
  0.20031078]
000000378139.jpg
[ 1.3101822  -0.8911558   0.14053605 ...  1.0964019  -0.9369396
 -0.6209344 ]
000000378244.jpg
[ 0.45599163 -0.5393243  -0.02807739 ...  0.5948602   1.1198297
 -0.8181912 ]
000000378284.jpg
[-0.32155672  0.99080837  0.45718172 ...  0.82976305  0.04241711
  0.37806052]
000000378453.jpg
[ 0.7483066  -0.27566558 -0.31842902 ...  0.11911577 -0.5462763
 -1.6107259 ]
000000378454.jpg
[ 0.11726632 -0.7882496   0.39292675 ...  1.2079788   0.9624599
 -1.5304788 ]
000000378515.jpg
[-0.02786979  1.9686812  -0.07966949 ...  0.6202684  -0.26106218
  0.43532634]
000000378605.jpg
[ 0.44730917  0.5987735  -0.87062526 ...  1.179

[ 0.14530209 -0.4530726  -0.71437854 ...  0.07870887  1.1292769
 -0.03044709]
000000389315.jpg
[-0.9636677  -0.1875683   0.07157453 ...  0.9468844   0.5899434
 -1.4659274 ]
000000389316.jpg
[ 0.53221965  0.9639827  -0.30327886 ...  0.37699753  0.06840311
 -0.596433  ]
000000389381.jpg
[ 0.17023121 -0.57838106 -0.22459334 ... -0.30651328  0.33783776
  0.7607176 ]
000000389451.jpg
[ 0.01001493  0.10226802 -0.1830551  ...  0.43816817 -0.01978572
  1.6317526 ]
000000389532.jpg
[ 0.50400835  0.85247695  0.6323006  ... -0.4733403   0.29788604
  0.09561763]
000000389566.jpg
[ 1.130699    0.7382975   0.49568897 ... -0.5641999   1.4956995
 -0.91512424]
000000389684.jpg
[ 1.4380679   0.37952226 -0.97646517 ... -0.07922981  0.36503413
 -0.5422882 ]
000000389804.jpg
[-0.7154173  -0.20552802 -1.5285435  ... -0.56759715  1.0892454
 -0.88955206]
000000389812.jpg
[-0.28964886  0.53775483  0.2692351  ... -0.19438508 -0.9733362
 -0.1040468 ]
000000389933.jpg
[-0.13566786  0.57958716  0.95286876 ... -0.7

[ 0.668827    1.0944074  -0.2312065  ... -0.7074193   0.7391799
 -0.33285964]
000000400044.jpg
[ 0.09085327 -0.33056206 -1.132355   ... -0.9818126   0.6670238
 -0.12373433]
000000400082.jpg
[ 0.17227198  0.07997713  1.2514795  ...  0.31993872  0.04946207
 -0.14004844]
000000400161.jpg
[-0.7848176  -0.3597364   0.60915786 ... -0.33226895 -0.35089812
 -0.3165169 ]
000000400367.jpg
[-0.25567985 -1.8505957  -0.36876175 ... -0.4752529  -0.26522133
  0.15470088]
000000400573.jpg
[ 0.16383548 -0.8580949  -0.30957618 ...  0.68598515 -1.4534535
 -0.19547263]
000000400794.jpg
[ 0.12762943 -0.02082501 -0.40615752 ... -0.14637528 -0.6302503
 -0.12558284]
000000400803.jpg
[ 0.17390466  0.36042425 -0.2332524  ...  1.0621789   0.06169789
 -0.29678622]
000000400815.jpg
[ 0.13948417  0.43727726 -0.02199546 ... -0.40090802  0.9687979
 -0.35937256]
000000400922.jpg
[ 1.2965796   0.31575704  1.0007213  ... -1.0802332  -0.02424425
 -0.7632091 ]
000000401244.jpg
[-0.23908131 -0.73405844 -0.09289479 ...  0.0

[ 0.73343503 -0.27382487 -0.96500707 ... -0.24452543  0.79073334
  0.19669552]
000000409630.jpg
[ 1.1745498  -0.99890375  1.1131748  ... -0.31533304 -0.01918478
 -0.09917381]
000000409867.jpg
[ 0.9985925   0.489338    0.43538067 ... -0.06284845  0.25300342
 -0.02666226]
000000410221.jpg
[ 0.44729364 -0.41187227 -1.4058735  ...  0.400269    0.5655567
  0.19366273]
000000410428.jpg
[ 1.737764    0.6864762   0.6945761  ... -0.45406458  0.44088945
  0.16928096]
000000410456.jpg
[-0.22650374 -1.0438399  -0.7321825  ...  0.42463762  0.12471296
 -0.03490588]
000000410487.jpg
[-0.81700706  0.59228015 -0.70322365 ...  0.8680648  -0.2458678
 -0.98508304]
000000410496.jpg
[-1.4814857   0.09355616 -0.5926495  ...  0.7955043  -0.20516293
 -1.3909346 ]
000000410510.jpg
[-1.2056355  -0.48630884 -0.57070166 ...  0.3353679   0.00515151
 -1.0533926 ]
000000410612.jpg
[-0.05500808  0.25200477 -0.9719352  ... -0.269832    0.53981483
  0.5829561 ]
000000410650.jpg
[-0.6219005   0.46967244 -0.6645518  ...  

[ 0.0177256   0.28003407 -0.27476195 ...  0.49138916 -0.50420517
 -1.9516039 ]
000000419408.jpg
[ 0.68359464 -1.4399155   0.71396667 ...  0.17991038  0.76197344
 -0.04183952]
000000419601.jpg
[-0.35281506  0.5720352   0.81778747 ...  0.15484995 -0.52222025
  0.8552211 ]
000000419653.jpg
[ 0.2333447   0.8589023  -0.23503022 ... -0.10997213  0.7150256
  0.15169023]
000000419882.jpg
[ 0.37942183  1.3441756  -0.44205245 ... -0.1414323  -0.43678984
 -0.5448849 ]
000000419974.jpg
[ 0.6290455  -0.11192841  0.43160072 ...  0.78846174  0.53695065
 -0.73982435]
000000420069.jpg
[ 0.841553   -0.54688126 -0.44588074 ...  0.42831337  0.55276847
 -0.5561677 ]
000000420230.jpg
[ 1.2671577  -0.09461381 -0.16046262 ...  1.1206005   0.35826448
 -0.55130327]
000000420281.jpg
[-0.5094472  -0.48547378  0.37586182 ...  0.6148125  -0.9702248
 -0.00998709]
000000420472.jpg
[ 0.8410199  0.6317863  1.3763345 ...  0.3536722 -0.3572519 -1.213731 ]
000000420840.jpg
[-0.65038955 -0.32540917 -0.36581865 ... -0.01254

[ 0.7607027  -1.3910145  -0.34153765 ...  0.5090731  -0.15292497
  0.22554347]
000000430073.jpg
[ 1.4247375   1.0285563  -0.1413949  ...  0.3924746   0.84582895
  0.05710395]
000000430286.jpg
[-0.23581937  0.59944975 -0.18918045 ...  0.9042157  -0.01372769
 -0.29272237]
000000430377.jpg
[ 0.38342756  1.0645968  -0.13392444 ... -0.9055868   0.7141951
 -0.22096275]
000000430871.jpg
[-0.00831923  0.677549   -0.7564351  ...  0.9887763  -1.3650862
  1.2846379 ]
000000430875.jpg
[ 1.5914075   0.06617964  0.01978256 ... -1.0963185  -1.4084307
 -1.1714935 ]
000000430961.jpg
[ 0.12698548 -0.612776   -0.44624636 ... -0.17196366  0.5271085
 -0.23119108]
000000430973.jpg
[1.0239023  0.01649046 0.37093067 ... 1.177846   0.9426733  0.827696  ]
000000431140.jpg
[ 0.50876504  0.6655142  -0.5762971  ...  0.25126     0.8971472
 -0.8387386 ]
000000431545.jpg
[-0.03061116 -0.96090937 -0.1280127  ...  0.626757    0.040758
 -0.14702985]
000000431568.jpg
[ 0.29018572  0.69247955  1.3450108  ...  1.4418554   

[ 0.13901696 -1.2427349   0.06317778 ...  0.23387623  0.614696
 -0.6234759 ]
000000441442.jpg
[-1.511995    0.4879752  -0.7097446  ... -0.67039555 -0.23040727
 -0.78333646]
000000441468.jpg
[ 1.2600132   0.2944772  -0.26422015 ...  0.52844447  0.2912862
 -1.0861415 ]
000000441491.jpg
[-0.11225381  0.03539645  0.17396146 ...  0.9359962  -0.2855587
  0.08152041]
000000441543.jpg
[-0.57302046 -0.43049446 -0.23647875 ...  1.2323939   0.05723985
 -0.7150961 ]
000000441553.jpg
[-0.04256557  0.9943664   0.5110399  ...  0.56581765 -0.4517672
 -1.5158191 ]
000000441586.jpg
[-0.10864444  0.2538351   0.6147629  ...  0.11368553 -1.6681603
 -1.4701844 ]
000000442009.jpg
[-0.26127255  0.72811407  0.40924087 ...  0.6687988   0.40179488
 -0.17786947]
000000442161.jpg
[-0.6660048  -0.4353606  -0.98892254 ...  1.0700761  -0.26064613
  1.1698059 ]
000000442306.jpg
[-0.5229986   0.45749208 -0.30741248 ...  0.16000302  0.04347683
 -0.64785707]
000000442323.jpg
[-0.10809873  0.66771215 -0.686068   ...  0.14

[-0.34630406 -1.0588475   0.14812453 ... -0.04437073  0.6257912
  0.17712033]
000000451090.jpg
[ 8.0960971e-01  7.9498881e-01 -3.7143564e-01 ...  1.1764361e+00
  4.9386406e-05 -2.6869503e-01]
000000451144.jpg
[ 0.24552439  0.15473925  0.62524366 ... -0.18835877  0.82969236
  0.24680342]
000000451150.jpg
[ 0.18487172  0.19510777 -0.21072923 ...  1.1642759  -0.3540936
 -1.4581844 ]
000000451155.jpg
[ 0.22222216 -0.5292379   0.584008   ...  1.5547782   0.7441503
 -0.8117556 ]
000000451308.jpg
[ 0.06369855  0.5014663   0.14441596 ... -0.03143695  0.88166606
 -1.7447275 ]
000000451435.jpg
[ 0.13188362 -0.71842635  0.61309856 ...  0.74738365  0.63944554
 -0.05350555]
000000451571.jpg
[-0.09891453  0.79116684 -0.20134355 ...  2.3620217   0.8449539
  0.4256544 ]
000000451693.jpg
[-0.14999136  0.62132174  0.6841741  ...  1.4384195   1.4507432
 -0.42574564]
000000451714.jpg
[ 0.20451167  0.04118529 -0.3503124  ... -0.12051     0.0991129
  0.2242    ]
000000451879.jpg
[-0.3457986   0.57014894  0.

[ 1.0103247   0.27371234  1.2410505  ... -0.31984583  0.34652835
 -1.0536388 ]
000000459809.jpg
[ 0.39167577  0.5463552   0.5633799  ... -0.38775697  0.3929754
  0.8009451 ]
000000459887.jpg
[-0.06723443  0.47928852 -0.60894656 ...  0.10291249 -0.55651456
  0.2640703 ]
000000459954.jpg
[ 0.32203278 -0.13591015 -0.19321477 ... -0.34374917 -0.32590628
  0.44188857]
000000460147.jpg
[ 1.661053   -0.37251148 -1.5239655  ... -0.3213162   0.2532495
 -1.0523745 ]
000000460160.jpg
[ 0.15176828  0.44180977  0.14933583 ...  1.4069037  -0.01805653
  0.33520448]
000000460229.jpg
[ 0.42583025  0.9825194  -0.70597756 ...  0.8922354  -0.2693999
 -0.5471729 ]
000000460333.jpg
[-0.3488195   0.5924973   0.27422753 ...  0.23377581 -0.14968337
 -0.35862803]
000000460347.jpg
[ 0.70501226 -0.36584154 -0.03576957 ...  0.98808575  0.49444175
  0.30094078]
000000460379.jpg
[ 1.1595522  -0.09545563  0.13220334 ...  0.22764029  0.32481244
 -1.0629311 ]
000000460494.jpg
[ 0.6174793  -0.33711419  1.210605   ...  0

[ 0.47818196  1.28197     0.332775   ...  1.0412991   0.82161283
 -0.46758762]
000000468505.jpg
[ 0.09108947  0.4080956  -0.2368725  ... -0.42149138 -0.6741093
 -0.5482765 ]
000000468577.jpg
[-0.70626557  0.8753648   0.9413121  ... -0.2552945  -0.733243
 -1.3479195 ]
000000468632.jpg
[ 0.48792255 -1.2059145  -0.19962195 ...  0.35822582  0.697207
 -1.1596506 ]
000000468925.jpg
[-0.66244954  0.3283046  -0.3676748  ...  0.8746468   0.14645682
 -1.3766934 ]
000000468954.jpg
[ 0.36745185  0.47246695  0.11378104 ...  0.2663948   0.6208548
 -0.07126039]
000000468965.jpg
[-0.00300197  1.4743423   0.21924445 ...  1.6404601   0.6719836
 -0.08033383]
000000469067.jpg
[ 0.22242665  0.28438187  0.7130035  ...  1.1620153  -0.14684393
 -1.3964267 ]
000000469174.jpg
[ 0.973384   -0.6071791  -1.3853613  ...  0.2619225   0.03982643
 -0.1938707 ]
000000469192.jpg
[-0.3840379   0.09019992 -0.20549467 ... -0.9506615  -0.636581
  0.8564198 ]
000000469246.jpg
[-0.06301238  1.3328737   0.67024726 ...  0.45279

[-4.0875608e-03 -4.9996907e-01  6.3544605e-05 ...  1.8130609e-01
 -1.8451215e-01 -3.1341715e-03]
000000478136.jpg
[-0.6137237   0.5725517  -0.39775395 ...  1.4842123  -1.0961925
 -0.7614085 ]
000000478286.jpg
[ 0.47363228  1.9274186  -0.06951588 ...  0.07253652 -0.6821671
 -0.6661186 ]
000000478393.jpg
[ 0.3755566   0.2280899   0.60949963 ...  1.3060737   0.18544519
 -0.34991756]
000000478420.jpg
[ 0.70939976  1.312598    0.06081364 ...  0.02257092  0.6823322
 -1.0079961 ]
000000478474.jpg
[ 0.2233673   0.980378    0.02383223 ... -1.4483339   1.8613762
 -0.85920954]
000000478721.jpg
[ 0.7321646   0.5711464   0.15966928 ...  0.15242124  0.42640305
 -0.7093426 ]
000000478862.jpg
[-0.10418077  0.8108828   0.23957665 ...  0.48487964 -0.2006533
  0.3922969 ]
000000479030.jpg
[ 0.39324778 -0.22869821  0.37135768 ...  0.67114615  0.9593466
 -1.7246487 ]
000000479099.jpg
[-0.45386034 -0.00544275  0.53988564 ...  1.1135342   0.920913
 -0.47536898]
000000479126.jpg
[ 0.66512835 -0.42913076  0.27

[ 0.5461329   0.26631057 -0.9298348  ... -0.7713744  -1.0884364
 -0.04547131]
000000488736.jpg
[-0.24215496  0.88688344  0.08402567 ... -0.9056797   0.08500554
  0.07222521]
000000489014.jpg
[-0.49297535 -0.06251379 -0.12638865 ...  1.0672486  -0.24550487
 -0.21583056]
000000489046.jpg
[ 0.41677585 -0.625612    0.49031666 ... -0.8731902  -0.6305395
  0.13765292]
000000489091.jpg
[-0.20108522  0.73631346 -0.14989294 ...  0.07081416  0.6600662
 -0.43693954]
000000489305.jpg
[-0.47883907  0.06776174 -0.7789992  ... -0.9414253  -0.04056584
  0.8109346 ]
000000489339.jpg
[ 0.3379022  -1.2442536  -0.31527382 ...  0.62681776  0.29387033
  0.26238534]
000000489611.jpg
[-0.01236051 -0.16841826  1.258283   ...  0.19648041  0.35212874
  0.17151877]
000000489764.jpg
[ 1.1121778  -0.36637133  0.46297932 ... -1.0830184   0.18169077
 -0.04970982]
000000489842.jpg
[-0.24291313  1.0982089   1.269902   ...  0.8268295   0.42487654
  0.40939337]
000000489924.jpg
[-0.60046846 -0.344559    0.14631392 ... -0

[ 0.24212785  0.77774316 -0.2205414  ...  0.93473583 -0.58384645
 -1.2623506 ]
000000499313.jpg
[-0.3273391   1.4209163   0.343895   ...  1.1997885   0.43753666
 -0.16942072]
000000499622.jpg
[-0.86763024  0.09003719  0.04321321 ... -0.79705596 -1.5241117
 -0.9505149 ]
000000499768.jpg
[ 0.48227498  0.09757371 -1.123339   ...  0.13591062 -0.8813485
 -0.8938291 ]
000000499775.jpg
[ 1.3951391  -0.6590208  -0.43036324 ...  1.4919314   0.6081661
 -0.22333571]
000000500049.jpg
[ 0.2645934   0.5271049  -0.82196    ...  0.63168275 -1.1046591
  0.17904355]
000000500211.jpg
[ 0.8872036   0.75851774 -0.04271139 ... -0.44004136  1.1622406
 -0.15585384]
000000500257.jpg
[ 0.91257447  0.46939552  0.39472917 ... -0.6836871  -0.68130314
  0.0704801 ]
000000500270.jpg
[ 0.23912612 -0.8776795   0.35312206 ... -0.89139354 -0.47789294
 -0.41806307]
000000500423.jpg
[ 0.20335098 -0.5353604   0.19608779 ...  1.223999   -0.37124044
 -1.4860636 ]
000000500464.jpg
[-0.95964    -0.16756605 -0.6870627  ...  0.6

[-0.35713604 -1.0859894  -0.38767952 ...  0.2658387  -0.41838038
 -0.29166862]
000000509451.jpg
[ 0.8583685  -1.0761324   0.29298034 ... -0.43502158 -0.46022004
 -0.7153403 ]
000000509656.jpg
[ 0.75372815  0.95740813  0.27270412 ...  0.8621933  -0.6242212
 -0.6528587 ]
000000509699.jpg
[-0.10411737  0.1131021   0.11342221 ...  0.13325378  0.18706924
  0.09323031]
000000509719.jpg
[ 0.7503014  -0.56885177  0.45135143 ... -0.192216   -1.0330265
 -1.1558809 ]
000000509735.jpg
[ 1.9436091   0.07711402  0.22335505 ...  0.523628   -0.36119542
 -1.6613686 ]
000000509824.jpg
[-0.0244447   0.4154683   1.0681721  ... -0.10060876  0.6179653
 -0.36726   ]
000000510095.jpg
[-0.0452335   0.52904236 -0.5145721  ... -0.3151267  -0.2523262
 -0.55529666]
000000510329.jpg
[ 1.7157634  -0.7719954  -0.8413767  ...  0.9080779   1.2725636
 -0.49557167]
000000511076.jpg
[-0.0047737   0.5090628   0.85488695 ... -0.01793141 -1.0075381
  1.5083809 ]
000000511321.jpg
[ 0.12735756 -0.4341242  -0.49492064 ...  1.59

[-0.22716567  0.36485982 -1.309436   ... -0.8608014  -0.38566074
  0.9391679 ]
000000520531.jpg
[ 0.46001282  0.04663578  1.020533   ...  0.07644133 -0.34071982
 -0.89186263]
000000520659.jpg
[ 0.05990224 -0.82560533  0.20236696 ...  0.28149527  0.59705544
  0.17040789]
000000520707.jpg
[ 1.1976343   0.62267727  0.07513762 ... -0.19870335 -1.1507047
 -1.0775905 ]
000000520832.jpg
[-0.24626262  0.6810689  -0.5547674  ... -1.0992279   1.2294538
  0.87085307]
000000520871.jpg
[-0.23373751  0.30288085  0.9709191  ...  1.8716756   0.221826
 -0.29529017]
000000520910.jpg
[-0.2501509   1.2396001  -0.3481705  ...  0.25177637 -0.08528754
  0.57707584]
000000521052.jpg
[ 0.13698465 -1.326363    0.89594626 ...  1.0018399   0.2179388
  0.09580113]
000000521141.jpg
[-0.21386528 -1.2167573  -0.24148314 ...  1.132336   -1.7196507
 -0.35079005]
000000521231.jpg
[0.9355925  0.4800298  0.40294328 ... 0.8937436  1.2264216  0.04631691]
000000521259.jpg
[-0.24697512  0.3913876  -0.3812358  ...  0.32152727 

[0.04468974 0.3704273  0.7443725  ... 1.059324   1.0279901  0.0223003 ]
000000530466.jpg
[-3.6023483e-01  4.7635323e-01  9.8143721e-01 ...  3.6437251e-04
  3.2321537e-01 -1.3477862e+00]
000000530470.jpg
[ 1.5023472  -0.49930137  1.2306025  ... -0.43564236  0.44814938
  0.51599145]
000000530624.jpg
[ 0.21207641  0.05164628  0.65270454 ...  0.64062065 -0.35586682
 -0.9209688 ]
000000530820.jpg
[-0.54766077 -0.4117179   0.5216295  ...  0.4414386  -0.73172
 -0.429141  ]
000000530836.jpg
[-0.13336495  1.9104396  -0.01508111 ... -1.347605    0.72192466
  0.18290897]
000000530854.jpg
[-0.07603582  0.3330948   0.0900036  ...  0.5742966   0.60495234
 -0.9643643 ]
000000530975.jpg
[ 0.8343458   0.26700342  0.3150393  ... -0.11849153 -0.13979112
 -0.437129  ]
000000531036.jpg
[ 1.2585241   0.06706586 -1.1191632  ...  1.4410175   0.10907736
 -0.06073289]
000000531134.jpg
[ 1.1609157   0.10857204 -0.82024723 ... -0.09003957 -0.75133663
 -0.52363235]
000000531135.jpg
[ 0.03392231 -0.32761344  0.2263

[ 0.5292755   0.4132083   0.0203425  ... -0.40418163  0.3109096
  0.773421  ]
000000542073.jpg
[-0.06911583  0.74579453  0.33764184 ...  0.61852336  0.7378045
  0.6741943 ]
000000542089.jpg
[-0.48991844  1.2563039  -1.2758409  ...  0.31293204  0.702548
 -0.4944293 ]
000000542127.jpg
[-0.06016103 -0.39639094 -0.4465305  ... -0.2879717   1.1054636
 -0.9622223 ]
000000542423.jpg
[-0.29977015 -1.6364654   0.22251502 ...  0.36930954 -1.1973617
  0.63840663]
000000542625.jpg
[ 1.4766994  -0.83336616 -0.545595   ...  0.01741553 -0.6860875
  0.7358465 ]
000000542776.jpg
[-0.27439153 -0.22042908 -0.46050656 ... -0.50129193  1.171427
  0.10517838]
000000542856.jpg
[ 0.70450157 -0.30328473  0.13055003 ...  0.84858197  0.7081309
  0.4342304 ]
000000543043.jpg
[-0.12654404  0.7756768   0.17001785 ... -0.02427982 -0.8692021
  0.22858277]
000000543047.jpg
[-0.25471556  0.88199437  0.10636497 ...  1.0837604   0.84419763
  0.60507137]
000000543300.jpg
[ 1.3883177   0.7752914  -0.9983196  ...  0.8392152

[-0.7026913   0.34581834 -0.6549036  ... -0.22539432 -1.1703674
  0.6353325 ]
000000552842.jpg
[-0.9632689  -0.8883837   0.22540586 ... -0.00796935  0.15839286
 -1.2390106 ]
000000552883.jpg
[-0.894492    1.5434706  -0.10481001 ...  0.11837594 -0.01861227
 -0.17774737]
000000552902.jpg
[ 1.0473497   0.27333346  0.821674   ...  0.01451402 -0.94501257
  0.25627717]
000000553094.jpg
[ 0.53914684 -0.6880028  -0.3489235  ...  0.39493027  0.27715772
 -0.5217259 ]
000000553221.jpg
[-0.69719833 -0.8888352  -0.11541357 ...  0.45856395 -0.03037867
  0.02967625]
000000553339.jpg
[ 0.34976894  0.93786716 -1.1393864  ... -0.38063133  0.83109987
 -1.715084  ]
000000553511.jpg
[ 0.66331273 -0.38727018 -0.1431097  ...  0.0063468  -0.30920023
 -0.1709696 ]
000000553664.jpg
[ 0.83236927 -0.1188433   1.0623565  ...  0.30749178  0.8021792
  0.9560826 ]
000000553669.jpg
[ 0.4531128  -2.0223556   1.1037035  ...  0.26558068  0.0591226
  0.04315158]
000000553731.jpg
[-0.05874947  0.65887105  0.20726874 ...  1

[ 0.04434659 -0.68168235  0.55023694 ...  0.3658095   0.2508883
 -0.46935537]
000000562818.jpg
[ 0.683679   -0.30598608  0.10488573 ...  0.1699947   1.0837647
 -0.5926207 ]
000000562843.jpg
[-0.72793293 -0.55473006  0.11768091 ...  1.1946102   0.51840013
  0.7884284 ]
000000563267.jpg
[-0.44813168  0.90525496 -0.31642938 ...  0.88443995  0.08477021
  0.04553105]
000000563281.jpg
[ 0.22377165  0.43842885  1.5270787  ... -0.79540974 -0.2634686
  0.8732132 ]
000000563349.jpg
[-0.44738346 -1.2474216  -0.5998496  ...  0.46883348  0.52102506
 -0.11411996]
000000563470.jpg
[ 0.50414264 -0.3422379  -0.6318232  ...  0.54274464  0.4049401
  0.07188839]
000000563603.jpg
[ 1.1833782  -0.4161158   1.0221958  ...  0.77577645  0.20277329
 -1.3303119 ]
000000563604.jpg
[ 1.0348315  -1.0560707  -0.6627768  ... -1.6544867   1.1596097
 -0.02459277]
000000563648.jpg
[ 0.1120611  -1.7279842   0.71781385 ... -0.35209268  0.4737349
  0.44708288]
000000563653.jpg
[ 0.65273064 -0.78056806  0.09379245 ...  0.31

[ 1.0215259  -0.9620381  -0.56917214 ...  0.05782954  0.11719751
 -0.806575  ]
000000572303.jpg
[ 0.3777368   1.0877196   0.03089178 ...  0.20924842 -0.3776721
 -1.0459522 ]
000000572388.jpg
[ 0.83897394  0.6681373   0.9673813  ...  0.78991264 -0.9379064
 -0.7760056 ]
000000572408.jpg
[ 1.7600254  -0.12038966  0.95814323 ...  0.08024715  1.5115621
 -0.10518162]
000000572462.jpg
[ 0.81002575  1.7982168   0.08528657 ...  0.18472056 -0.41491997
  0.9079935 ]
000000572517.jpg
[0.8071841  0.01934901 0.28843775 ... 1.2560246  0.8572051  0.0668011 ]
000000572555.jpg
[-0.44111714  1.095497   -0.45271975 ...  0.72883976  0.05264921
 -1.4009671 ]
000000572620.jpg
[ 0.3832668  -1.3633168  -0.71292496 ... -0.13750893  0.39975336
 -0.34536448]
000000572678.jpg
[-0.8818551   0.86219245  0.23562597 ...  0.26517147 -0.14504933
  0.24769276]
000000572900.jpg
[-0.01685563 -0.08363853 -0.27131435 ...  0.759745    0.4839371
 -0.5995212 ]
000000572956.jpg
[-0.70456237 -0.6080575  -0.8262814  ... -0.8969806